name: autoBackup

on:
  push:
    # paths:
    #   - '.github/workflows/autoBackup.yml'
    repositories:
      - owner: binary
        name: cdle

jobs:

  backup:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 获取更新日期
        run: |
          v=`curl https://raw.githubusercontent.com/cdle/binary/main/compile_time.go --silent | tr -cd "[0-9]"`
          echo "version=$v" >> $GITHUB_ENV
          creatDate=$((v/1000))
          echo "compile_time=$(date '+%Y-%m-%d' -d @$creatDate)"  >> $GITHUB_ENV

      - name: 获取最新文件
        run: git clone https://github.com/cdle/binary.git

      - name: 作为备份上传
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "备份日期${{ env.compile_time }}"
          automatic_release_tag: "版本号${{ env.version }}"
          files: binary/

      - name: 作为最新上传
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "最新版傻妞"
          automatic_release_tag: "latest"
          prerelease: false
          files: binary/

  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 9
          keep_minimum_runs: 5