name: autoBackup

on:
  # push:
  #   paths:
  #     - '.github/workflows/autoBackup.yml'
  repository_dispatch:
    types: [backup]

jobs:

  backup:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 获取更新日期
        run: |
          v=`curl https://raw.githubusercontent.com/cdle/binary/main/compile_time.go --silent | tr -cd "[0-9]"`
          echo "version=$v" >> $GITHUB_ENV
          creatDate=$((v/1000))
          echo "compile_time=$(date '+%Y-%m-%d' -d @$creatDate)"  >> $GITHUB_ENV

      - name: 获取最新文件
        run: git clone https://github.com/cdle/binary.git

      - name: 作为备份上传
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: "true"
          name: "备份日期${{ env.compile_time }}"
          tag: "版本号${{ env.version }}"
          artifacts: "binary/*"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 作为最新发布
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: "true"
          name: "最新版傻妞"
          tag: "latest"
          artifacts: "binary/*"
          token: ${{ secrets.GITHUB_TOKEN }}