name: Monitor Other Repository

on:
  schedule:
    - cron: '12 */6 * * *'   # 每6小时执行一次
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check if other repository has new commits
      id: check_commit
      run: |
        last_sha=$(cat last_sha.txt)
        latest_sha=$(curl -H "Authorization: token ${{ secrets.PAT }}" \
              https://api.github.com/repos/cdle/binary/commits/main \
              | grep -oP '(?<="sha": ")[^"]+' | head -n 1)
        if [[ $latest_sha != $last_sha ]]; then
          echo "New commit detected in other repository!"
          echo "$latest_sha" > last_sha.txt
          echo "::set-output name=trigger_build::true"
        else
          echo "No new commit in other repository."
          echo "::set-output name=trigger_build::false"
        fi

    - name: Trigger build
      if: steps.check_commit.outputs.trigger_build == 'true'
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/callacat/sillyGirl-Backup/dispatches \
          -d '{"event_type": "backup"}'

    - name: Commit changes
      if: steps.check_commit.outputs.trigger_build == 'true'
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add last_sha.txt
        git commit -m "Update last_sha.txt"

    - name: Push changes
      if: steps.check_commit.outputs.trigger_build == 'true'
      uses: ad-m/github-push-action@master
      with:
        branch: main
        github_token: ${{ secrets.PAT }}
        force_with_lease: true